version: '3'
services:
  web:
    build: .
    container_name: megapolis-front
    logging:
      driver: gelf
      options:
        gelf-address: "udp://graylog.amberlight.io:12201"
        tag: "megapolis-front"
    ports:
      - "8009:80"
